=== sirivardhan/api-order-document-images/src/main/api/schemas/obtainIPM_get_response_schema.json
{
  "$id": "http://example.com/example.json",
  "type": "array",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "items": {
    "$id": "http://example.com/example.json/items",
    "type": "object",
    "properties": {
      "orderNumber": {
        "$id": "http://example.com/example.json/items/properties/orderNumber",
        "type": "string",
        "title": "The Ordernumber Schema ",
        "default": "",
        "examples": [
          "9266953"
        ]
      },
      "customerPONumber": {
        "$id": "http://example.com/example.json/items/properties/customerPONumber",
        "type": "string",
        "title": "The Customerponumber Schema ",
        "default": "",
        "examples": [
          "91913"
        ]
      },
      "invoiceNumber": {
        "$id": "http://example.com/example.json/items/properties/invoiceNumber",
        "type": "string",
        "title": "The Invoicenumber Schema ",
        "default": "",
        "examples": [
          "NV-12345"
        ]
      },
      "docType": {
        "$id": "http://example.com/example.json/items/properties/docType",
        "type": "string",
        "title": "The Doctype Schema ",
        "default": "",
        "examples": [
          "AKN"
        ]
      },
      "documentURLs": {
        "$id": "http://example.com/example.json/items/properties/documentURLs",
        "type": "array",
        "items": {
          "$id": "http://example.com/example.json/items/properties/documentURLs/items",
          "type": "object",
          "properties": {
            "documentURL": {
              "$id": "http://example.com/example.json/items/properties/documentURLs/items/properties/documentURL",
              "type": "string",
              "title": "The Documenturl Schema ",
              "default": "",
              "examples": [
                "http://CBIGDCPIPMW002.cbi.net/ibpmdata/IBPMSessionData/_B85244DB_8286_4DB7_98A7_9BEBFDB 7D90B__6200180/AcordeContextExport/img810/img811.jpg"
              ]
            }
          }
        }
      }
    }
  }
}

=== sirivardhan/api-order-document-images/src/main/api/examples/obtainIPM_get_response_example.json
[
  {
    "customerPONumber": "91913",
    "docType": "AKN",
    "documentURLs": [
      {
        "documentURL": "http://CBIGDC-PIPMW002.cbi.net/ibpmdata/IBPMSessionData/_7F86AEE6_F233_466F_B509_AC49795E0BD5__6295452/AcordeContextExport/imgDE3/imgDE4.jpg"
      }
    ],
    "invoiceNumber": "0",
    "orderNumber": "9266953"
  },
  {
    "customerPONumber": "91913",
    "docType": "ASN",
    "documentURLs": [
      {
        "documentURL": "http://CBIGDC-PIPMW002.cbi.net/ibpmdata/IBPMSessionData/_7F86AEE6_F233_466F_B509_AC49795E0BD5__6295452/AcordeContextExport/imgDE5/imgDE6.jpg"
      }
    ],
    "invoiceNumber": "0",
    "orderNumber": "9266953"
  },
  {
    "customerPONumber": "91913",
    "docType": "INV",
    "documentURLs": [
      {
        "documentURL": "http://CBIGDC-PIPMW002.cbi.net/ibpmdata/IBPMSessionData/_7F86AEE6_F233_466F_B509_AC49795E0BD5__6295452/AcordeContextExport/imgDE7/imgDE8.jpg"
      }
    ],
    "invoiceNumber": "7328967",
    "orderNumber": "9266953"
  }
]

=== sirivardhan/api-order-document-images/src/test/resources/getCallResponse.json
[
  {
    "customerPONumber": "91913",
    "docType": "AKN",
    "documentURLs": [
      {
        "documentURL": "http://CBIGDC-PIPMW002.cbi.net/ibpmdata/IBPMSessionData/_BA2656A2_CCA9_4957_A521_F9AED9F44BC7__6295674/AcordeContextExport/imgE30/imgE31.jpg"
      }
    ],
    "invoiceNumber": "0",
    "orderNumber": "9266953"
  },
  {
    "customerPONumber": "91913",
    "docType": "ASN",
    "documentURLs": [
      {
        "documentURL": "http://CBIGDC-PIPMW002.cbi.net/ibpmdata/IBPMSessionData/_BA2656A2_CCA9_4957_A521_F9AED9F44BC7__6295674/AcordeContextExport/imgE32/imgE33.jpg"
      }
    ],
    "invoiceNumber": "0",
    "orderNumber": "9266953"
  },
  {
    "customerPONumber": "91913",
    "docType": "INV",
    "documentURLs": [
      {
        "documentURL": "http://CBIGDC-PIPMW002.cbi.net/ibpmdata/IBPMSessionData/_BA2656A2_CCA9_4957_A521_F9AED9F44BC7__6295674/AcordeContextExport/imgE34/imgE35.jpg"
      }
    ],
    "invoiceNumber": "7328967",
    "orderNumber": "9266953"
  }
]
